source 'https://rubygems.org'
gem 'asciidoctor-diagram'
gem 'asciidoctor-latex'
gem 'asciidoctor-pdf-cjk'
gem 'asciidoctor-pdf'
gem 'asciidoctor'
gem 'coderay'
gem 'rake'
gem 'rouge'
gem 'rubyzip', '>= 1.0.0'
